CREATE DATABASE data_analysis_project;
USE data_analysis_project;
SELECT * FROM customer_behavior_analysis;

-- -------------------------------------------------------------
-- BUSINESS INSIGHT QUESTIONS
-- -------------------------------------------------------------

-- 1. Which category generate the highest revenue?
Select category, round(sum(purchase_amount)) as highest_revenue
from customer_behavior_analysis
group by category
order by highest_revenue DESC;

--  BUSINESS PROBLEM - Company doesn't know which category contributes the most to the revenue.
-- IMPACT : 
           -- Helps prioritize high-performing categories
           -- Optimizes inventory planning
           -- Improves marketing ROI
           
 -- 2. Are discounts profitable?
 Select discount_applied, round(sum(purchase_amount)) as total_revenue, round(avg(purchase_amount)) as avg_revenue
 from customer_behavior_analysis
 group by discount_applied;
 
-- BUSINESS PROBLEM : Discounts may reduce profit without increasing sale
-- IMPACT :
		   -- Identify effectiveness of discounts
           -- Reduce unnecessary discount costs
           -- Improve profit margins
           
-- 3. What is the total revenue generated by males and females customers? 
Select gender, round(sum(purchase_amount)) as revenue
from customer_behavior_analysis
group by gender;

-- BUSINESS PROBLEM : Lack of understanding revenue segmentation among genders
-- IMPACT :
		   -- Helps design targeted marketed campaign
           -- Improves customer segmenattion strategies
           -- Enhances personalization efforts
           
-- 4. Which customer used a discount but still spent more than the average purchase amount? 
Select customer_id, purchase_amount, discount_applied
from customer_behavior_analysis
where discount_applied = "Yes" AND purchase_amount > (Select round(avg(purchase_amount)) 
                         from customer_behavior_analysis)
order by purchase_amount desc
limit 10;

-- BUSINESS PROBLEM : Company cannot identify high spending customers who are also the discount users
-- IMPACT :
		   -- Identifies premium discount-sensistive customers
           -- Enables targeted discount campaigns
           -- Improves customer retention and revenue
           
-- 5. Which are the top/bottom 5 products with the highest average review rating? 
Select item_purchased, round(avg(review_rating)) as avg_ratings
from customer_behavior_analysis
group by item_purchased
order by avg_ratings desc
limit 5;

Select item_purchased, round(avg(review_rating)) as avg_ratings
from customer_behavior_analysis
group by item_purchased
order by avg_ratings asc
limit 5;

-- BUSINESS PROBLEM : No visibility into product performance based on customer validation
-- IMPACT :
		   -- Promotes high-performing products
           -- Improves low rated products
           -- Enhances customer experience
           
-- 6. Avergae purchase : Standard vs Express Shipping 
Select shipping_type, count(distinct customer_id) as order_placed,round(sum(purchase_amount), 2) as revenue ,round(avg(purchase_amount), 2) as avg_ratings
from customer_behavior_analysis
where shipping_type in ('Standard', 'Express')
group by shipping_type
order by revenue desc;

-- BUSINESS PROBLEM : Unclear if faster shipping leads to higher spending
-- IMPACT :
		   -- Helps optimize shipping pricing strategy
           -- Encourage premium shipping adoption
           -- Increase average order value
           
-- 7. Do subscribed customers spend more? Compare average speed and total revenue between subscribers and non-subscribers.
Select count(customer_id) as users, subscription_status, round(avg(purchase_amount),2) as avg_revenue, round(sum(purchase_amount),2) as total_revenue
from customer_behavior_analysis
group by subscription_status;

-- BUSINESS PROBLEM : The effectiveness of subscription program is unkn own
-- IMPACT :
		   -- Validate subscription model
           -- Improves customer loyalty rogram
           -- Increase customer retention
           
-- 8. Top 5 products with the highest discount usage %
Select item_purchased, count(item_purchased) as total_number_of_times_sold, count(case when discount_applied = "YES" then 1 end) as number_of_times_discount_applied,
count(case when discount_applied = "YES" then 1 end)*100/count(*) as discount_percent
from customer_behavior_analysis
group by item_purchased
order by discount_percent desc
limit 5;

-- BUSINESS PROBLEM : Some products maybe overly dependent on discount
-- IMPACT :
		   -- Identifies discount-driven products
           -- Help optimize pricing sstrategy
           -- Reduces profit margin loss
           
-- 9. Segment customers into new, returning and loyal based on their total numberr of previous purhases and show the count of each segment
Select case 
           when previous_purchases = '0' then 'New Customer'
           when previous_purchases between 1 and 15 then 'Returning Customer'
       else 'Loyal Customer'
end as customer_segment,
count(*) as customer_count
from customer_behavior_analysis
group by customer_segment;

-- BUSINESS PROBLEM : Lack of customer segmentatiion leads to generic strategies
-- IMPACT :
		   -- Enables personalized marketing
           -- Increase conversion rates
           -- Improves retention strategies
           
-- 10. Top 3 most purchased products within each category
with cte as(
Select category, item_purchased, count(item_purchased) as No_of_purchases,
rank() over(partition by category order by count(item_purchased) desc) as rnk
from customer_behavior_analysis
group by category, item_purchased)
SELECT * from cte
where rnk <= 3;

-- BUSINESS PROBLEM : SCompany doesn't know about top-performing products in each category 
-- IMPACT :
		   -- Improves product placement and recommendations
           -- Helps inverntory optimization
           -- Increases sales through best-sellers
           
-- 11. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscibe?
Select case
           when previous_purchases > 5 then 'Repeat Buyers'
	   else 'Normal Buyers'
       end as customer_type, subscription_status, count(*) as customer_count
from customer_behavior_analysis
group by customer_type, subscription_status;

-- BUSINESS PROBLEM : Unclear realtionship between loyalty and subscription
-- IMPACT :
		   -- Improves subscription targeting
           -- Increases conversion tp paid progress
           -- Increase customer retention strategy
           
-- 12. What is the revenue contribution of each group
Select case
           when age between 18 and 25 then '18-25'
           when age between 26 and 35 then '26-35'
           when age between 36 and 50 then '36-50'
           else '51+'
		end as age_group, round(sum(purchase_amount),2) as total_revenue
from customer_behavior_analysis
group by age_group
order by total_revenue desc;

-- BUSINESS PROBLEM : No visibility into which age group contributes the most
-- IMPACT :
		   -- Enables age-based targeting
           -- Enhances marketing efficiency
          